### ISSUE TITLE
Running tests from outside test directory

### ISSUE THREAD

**Issue by pgrange** [Pamplemousse/audit-ssh-client-config#1]
When I try to run tests from outside of the test directory I see some errors.

```bash
#> git clone git@github.com:Pamplemousse/audit-ssh-client-config.git
Clonage dans 'audit-ssh-client-config'...
remote: Counting objects: 64, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 64 (delta 32), reused 64 (delta 32), pack-reused 0
Réception d'objets: 100% (64/64), 11.52 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (32/32), fait.
Vérification de la connectivité... fait.
#> cd audit-ssh-client-config/
#> ./tests/bash_unit tests/test_main.sh 
Running tests in tests/test_main.sh
tests/test_main.sh: ligne 3: ./test_password_authentication: Aucun fichier ou dossier de ce type
tests/test_main.sh: ligne 4: ./test_challenge_response_authentication: Aucun fichier ou dossier de ce type
tests/test_main.sh: ligne 5: ./test_host_key_algorithms: Aucun fichier ou dossier de ce type
tests/test_main.sh: ligne 6: ./test_kex_algorithms: Aucun fichier ou dossier de ce type
tests/test_main.sh: ligne 7: ./test_ciphers: Aucun fichier ou dossier de ce type
tests/test_main.sh: ligne 8: ./test_pubkey_authentication: Aucun fichier ou dossier de ce type
tests/test_main.sh: ligne 9: ./test_macs: Aucun fichier ou dossier de ce type
tests/test_main.sh: ligne 10: ./test_use_roaming: Aucun fichier ou dossier de ce type
Running test_each_message_is_displayed_only_once... SUCCESS ✓ 
```

I know that bash_unit changes current working directory of tests to the directory containing the test file. However, this is not the case when loading the test file itself so the ```source``` lines in test_main.sh are misinterpreted.

I would suggest to just remove this lines from test_main and simply recommand to run bash_unit with all test file:

```
./tests/bash_unit tests/test_*
```

Regards,

**Comment by Pamplemousse** [comment]
Thanks for the feedback.

I understand the problem, but I am not a huge fan of the proposed solution.

The reason is that the `teardown()` code is currently common to all the tests cases, and I did not want to duplicate it across multiple tests files.

Having a "single entrypoint" to my test suite, and including/importing the necessary content (using `source`) seemed to be the best way to go for this very specific reason.

**Comment by Pamplemousse** [comment]
@pgrange, please let me know what you think about the related PR.
Thanks.

**Comment by pgrange** [comment]
I understand your issue. May be something is missing in bash_unit... I'll think about.
